### ISSUE TITLE
[Bug]: Time format makes app crash on windows

### ISSUE THREAD

**Issue by jeromemoly** [cnumr/ecoindex_cli#124]
### What happened?

Time format used for the temp folders contains ":" and makes app crash on windows.

Modifying app.py line 146 with  `time_now = datetime.now().strftime("%Y-%m-%d %H-%M-%S")` solves the problem.

### Version

Above 3.6

### What OS do you use?

Windows

### Relevant log output

```shell
PS C:\Users\meh\code\ecoindex\ecoindex_cli\ecoindex_cli> ecoindex-cli analyze --url https://www.myurl.fr                                                                                                               📁️ Urls recorded in file `/tmp/ecoindex-cli/input/www.myurl.fr.csv`
There are 1 url(s), do you want to process? [Y/n]: y
1 urls for 1 window size
Processing  [####################################]  100%
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\meh\AppData\Roaming\Python\Python310\Scripts\ecoindex-cli.exe\__main__.py", line 7, in <module>
  File "C:\Users\meh\AppData\Roaming\Python\Python310\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Users\meh\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\meh\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\meh\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\meh\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\meh\AppData\Roaming\Python\Python310\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\meh\AppData\Roaming\Python\Python310\site-packages\typer\main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\meh\AppData\Roaming\Python\Python310\site-packages\ecoindex_cli\cli\app.py", line 155, in analyze
    Path(output_folder).mkdir(parents=True, exist_ok=True)
  File "C:\Python310\lib\pathlib.py", line 1173, in mkdir
    self._accessor.mkdir(self, mode)
OSError: [WinError 123] La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte: '\\tmp\\ecoindex-cli\\output\\www.myurl.fr\\2022-04-27 14:47:33.823536'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vvatelot** [comment]
Thanks @jeromemoly I finaly used the format `%Y-%d-%m_%H%M%S`
Is this OK for you?
