### ISSUE TITLE
[Bug]: Erreurs en utilisant une image docker

### ISSUE THREAD

**Issue by hrenaud** [cnumr/ecoindex_cli#158]
### What happened?

Je souhaite tester l'usage de `ecoindex-cli`, sans forcement installer Python sur mon post (mac).

J'ai donc créé un Dockerfile et un fichier requirement.txt contenant le package `ecoindex-cli`.

L'installation se passe bien, `ecoindex-cli --help` retourne bien le message attendu, mais `analyse`génère des erreurs.

# Fichiers

`Dockerfile`

```Dockerfile
FROM python:3.8

WORKDIR /usr/src/app

RUN mkdir /tmp/ecoindex-cli

VOLUME /tmp/ecoindex-cli

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
```
`requirements.txt`
```
ecoindex-cli
```

# Commands Docker
1. `docker build -t ecoindex-cli-python-app .` pour créer l'image ;
2. `docker run -it --rm --name ecoindex-cli-running-app ecoindex-cli-python-app` pour la lancer.

# Commands testées et générant des erreurs

1. `ecoindex-cli analyze --url http://www.ecoindex.fr`
2. `ecoindex-cli analyze --url http://www.ecoindex.fr --recursive --html-report`

Les logs sont plus bas ⬇️

### Version

Above 3.6

### What OS do you use?

Docker (mac)

### Relevant log output

```shell
`ecoindex-cli analyze --url http://www.ecoindex.fr`


📁️ Urls recorded in file `/tmp/ecoindex-cli/input/www.ecoindex.fr.csv`
There are 1 url(s), do you want to process? [Y/n]: y
1 urls for 1 window size with 4 maximum workers
Processing  [------------------------------------]  0/1    0%Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/undetected_chromedriver/dprocess.py", line 59, in _start_detached
    p = Popen([executable, *args], stdin=PIPE, stdout=PIPE, stderr=PIPE, **kwargs)
  File "/usr/local/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1585, in _execute_child
    and os.path.dirname(executable)
  File "/usr/local/lib/python3.8/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType


`ecoindex-cli analyze --url http://www.ecoindex.fr --recursive --html-report`

```log
You are about to perform a recursive website scraping. This can take a long time. Are you sure to want to proceed? [Y/n]: y
⏲️ Crawling root url http://www.ecoindex.fr -> Wait a minute!
-2022-07-21 11:20:26 [scrapy.utils.log] INFO: Scrapy 2.6.1 started (bot: scrapybot)
2022-07-21 11:20:26 [scrapy.utils.log] INFO: Versions: lxml 4.9.1.0, libxml2 2.9.14, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0, Twisted 22.4.0, Python 3.8.13 (default, Jul 12 2022, 12:32:46) - [GCC 10.2.1 20210110], pyOpenSSL 22.0.0 (OpenSSL 3.0.5 5 Jul 2022), cryptography 37.0.4, Platform Linux-5.10.104-linuxkit-x86_64-with-glibc2.2.5
2022-07-21 11:20:26 [scrapy.crawler] INFO: Overridden settings:
{'LOG_ENABLED': False}
📁️ Urls recorded in file `/tmp/ecoindex-cli/input/www.ecoindex.fr.csv`
There are 3 url(s), do you want to process? [Y/n]: y
3 urls for 1 window size with 4 maximum workers
Processing  [------------------------------------]  0/3    0%Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/undetected_chromedriver/dprocess.py", line 59, in _start_detached
    p = Popen([executable, *args], stdin=PIPE, stdout=PIPE, stderr=PIPE, **kwargs)
  File "/usr/local/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1585, in _execute_child
    and os.path.dirname(executable)
  File "/usr/local/lib/python3.8/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/undetected_chromedriver/dprocess.py", line 59, in _start_detached
    p = Popen([executable, *args], stdin=PIPE, stdout=PIPE, stderr=PIPE, **kwargs)
  File "/usr/local/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1585, in _execute_child
    and os.path.dirname(executable)
  File "/usr/local/lib/python3.8/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Process Process-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/undetected_chromedriver/dprocess.py", line 59, in _start_detached
    p = Popen([executable, *args], stdin=PIPE, stdout=PIPE, stderr=PIPE, **kwargs)
  File "/usr/local/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1585, in _execute_child
    and os.path.dirname(executable)
  File "/usr/local/lib/python3.8/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vvatelot** [comment]
Bonjour @hrenaud merci pour la remontée d'incident. Je vais regarder ça. Il semblerait qu'il y ait un problème avec docker et la gestion du multiprocessing. En attendant, si tu as besoin de tester avec du docker, peut être peux tu t'orienter vers le projet [ecoindex_api](https://github.com/cnumr/ecoindex_api) ?

**Comment by hrenaud** [comment]
@vvatelot je retente ma chance aujourd'hui et j'ai toujours des erreurs (d'autres)... Ce n'est toujours pas utilisable dans un docker ?

```
python --version
Python 3.10.8
```

Pas de `ecoindex-cli --version`, mais installé ce matin.

Lorsque je lance `ecoindex-cli analyze --url https://www.ecoindex.fr/` (ou toute autre méthode) j'ai 

```sh
ecoindex-cli analyze --url https://www.ecoindex.fr/
📁️ Urls recorded in file `/tmp/ecoindex-cli/input/www.ecoindex.fr.csv`
There are 1 url(s), do you want to process? [Y/n]: y
1 urls for 1 window size with 4 maximum workers
Processing  [####################################]  1/1  100%
Errors found: please look at /tmp/ecoindex-cli/logs/www.ecoindex.fr.log)

ExportFormat.csv
Traceback (most recent call last):

  File "/usr/local/bin/ecoindex-cli", line 8, in <module>
    sys.exit(app())

  File "/usr/local/lib/python3.10/site-packages/ecoindex_cli/cli/app.py", line 193, in analyze
    write_results_to_file(

  File "/usr/local/lib/python3.10/site-packages/ecoindex_cli/files.py", line 69, in write_results_to_file
    file.write()

  File "/usr/local/lib/python3.10/site-packages/ecoindex_cli/files.py", line 37, in write
    headers = self.results[0].__dict__

IndexError: list index out of range
```

et dans le log
`2022-12-16 12:32:32,843  -- https://www.ecoindex.fr/ -- expected str, bytes or os.PathLike object, not NoneType`

Il me manque des libraries ?

**Comment by vvatelot** [comment]
Hello @hrenaud désolé pour le délai de réponse...
Je viens de jeter un oeil. je viens de faire une PR qui va dans ce sens... Peux tu tester ?

#211

**Comment by vvatelot** [comment]
Au final @hrenaud penses tu qu'on puisse clôturer cette issue ?

**Comment by hrenaud** [comment]
tout à fait. L'erreur initiale ne survient plus et pour le reste, c'est bon aussi
