### ISSUE TITLE
[Bug]: Recursive crawling fails without any explanation

### ISSUE THREAD

**Issue by benel** [cnumr/ecoindex_cli#207]
### What happened?

First, I would like to thank you very much for these great and promising tools.

I fail however in using the `--recusive parameter` of the cli tool.

While the analysis of a single URI works well

```
~ ecoindex-cli analyze --url https://$$$.$$$.$$$                          
📁️ Urls recorded in file `/tmp/ecoindex-cli/input/$$$.$$$.$$$.csv`
There are 1 url(s), do you want to process? [Y/n]: 
1 urls for 1 window size with 8 maximum workers
Processing  [####################################]  1/1  100%
ExportFormat.csv
🙌️ File /tmp/ecoindex-cli/output/###.###.###/2022-14-12_102602/results.csv written !
```
 
the recursive analysis fails

```
~ ecoindex-cli analyze --url https://$$$.$$$.$$$ --recursive --html-report
You are about to perform a recursive website scraping. This can take a long time. Are you sure to want to proceed? [Y/n]: 
⏲️ Crawling root url https://$$$.$$$.$$$ -> Wait a minute!
-2022-12-14 10:23:53 [scrapy.utils.log] INFO: Scrapy 2.7.1 started (bot: scrapybot)
2022-12-14 10:23:53 [scrapy.utils.log] INFO: Versions: lxml 4.9.2.0, libxml2 2.9.14, cssselect 1.2.0, parsel 1.7.0, w3lib 2.1.1, Twisted 22.10.0, Python 3.10.8 (main, Oct 13 2022, 10:17:43) [Clang 14.0.0 (clang-1400.0.29.102)], pyOpenSSL 22.1.0 (OpenSSL 3.0.7 1 Nov 2022), cryptography 38.0.4, Platform macOS-12.6.1-x86_64-i386-64bit
2022-12-14 10:23:53 [scrapy.crawler] INFO: Overridden settings:
{'LOG_ENABLED': False}
Traceback (most recent call last):

  File "/Users/benel/Library/Python/3.10/bin/ecoindex-cli", line 8, in <module>
    sys.exit(app())

  File "/Users/benel/Library/Python/3.10/lib/python/site-packages/ecoindex_cli/cli/app.py", line 100, in analyze
    ) = get_file_prefix_input_file_logger_file(urls=urls)

  File "/Users/benel/Library/Python/3.10/lib/python/site-packages/ecoindex_cli/cli/arguments_handler.py", line 100, in get_file_prefix_input_file_logger_file
    file_prefix = urlparse(next(iter(urls))).netloc

StopIteration
```

Any help would be greatly appreciated.

### Version

Above 3.6

### What OS do you use?

Mac

### urls

On request, I can send them to you privately.

### Relevant log output

```shell
⏲️ Crawling root url https://$$$.$$$.$$$ -> Wait a minute!
-2022-12-14 10:23:53 [scrapy.utils.log] INFO: Scrapy 2.7.1 started (bot: scrapybot)
2022-12-14 10:23:53 [scrapy.utils.log] INFO: Versions: lxml 4.9.2.0, libxml2 2.9.14, cssselect 1.2.0, parsel 1.7.0, w3lib 2.1.1, Twisted 22.10.0, Python 3.10.8 (main, Oct 13 2022, 10:17:43) [Clang 14.0.0 (clang-1400.0.29.102)], pyOpenSSL 22.1.0 (OpenSSL 3.0.7 1 Nov 2022), cryptography 38.0.4, Platform macOS-12.6.1-x86_64-i386-64bit
2022-12-14 10:23:53 [scrapy.crawler] INFO: Overridden settings:
{'LOG_ENABLED': False}
Traceback (most recent call last):

  File "/Users/benel/Library/Python/3.10/bin/ecoindex-cli", line 8, in <module>
    sys.exit(app())

  File "/Users/benel/Library/Python/3.10/lib/python/site-packages/ecoindex_cli/cli/app.py", line 100, in analyze
    ) = get_file_prefix_input_file_logger_file(urls=urls)

  File "/Users/benel/Library/Python/3.10/lib/python/site-packages/ecoindex_cli/cli/arguments_handler.py", line 100, in get_file_prefix_input_file_logger_file
    file_prefix = urlparse(next(iter(urls))).netloc

StopIteration
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vvatelot** [comment]
Thanks for the report. You mention that you use python above 3.6. Could you try to update to python 3.10 ?
In the same time, could you send me the url of the website you are trying to analyze ? You can send it on vincent@lebondeveloppeur.fr

**Comment by vvatelot** [comment]
I can reproduce it ! I can reproduce it !!! :smile: 
OK, I try to find a fix !
