### ISSUE TITLE
[Bug]: Installation successful but not functional

### ISSUE THREAD

**Issue by fredlux55** [cnumr/ecoindex_cli#215]
### What happened?

Installation successful but not functional
On a fresh Ubuntu Server (and after apt update, apt upgrade) : 
```
$hostnamectl
 Static hostname: v6-ecoindex
       Icon name: computer-vm
         Chassis: vm
      Machine ID: f***4
         Boot ID: 3***8
  Virtualization: vmware
Operating System: Ubuntu 22.04.1 LTS              
          Kernel: Linux 5.15.0-56-generic
    Architecture: x86-64
 Hardware Vendor: VMware, Inc.
  Hardware Model: VMware20,1
```

```
Python 3 and pip versions : 
$python3 -V
Python 3.10.6
```

```
$pip --version
pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)
```

```
$pip install --user -U ecoindex-cli
  WARNING: The scripts f2py, f2py3 and f2py3.10 are installed in '/home/fred/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts fonttools, pyftmerge, pyftsubset and ttx are installed in '/home/fred/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script automat-visualize is installed in '/home/fred/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts cftp, ckeygen, conch, mailmail, pyhtmlizer, tkconch, trial, twist and twistd are installed in '/home/fred/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script tldextract is installed in '/home/fred/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script scrapy is installed in '/home/fred/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script ecoindex-cli is installed in '/home/fred/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed Automat-22.10.0 Pillow-9.3.0 PyDispatcher-2.0.6 PySocks-1.7.1 PyYAML-6.0 Scrapy-2.7.1 Twisted-22.10.0 async-generator-1.10 certifi-2022.12.7 cffi-1.15.1 click-spinner-0.1.10 constantly-15.1.0 contourpy-1.0.6 cryptography-38.0.4 cssselect-1.2.0 cycler-0.11.0 ecoindex-5.4.1 ecoindex-cli-2.15.2 ecoindex-scraper-2.11.1 exceptiongroup-1.0.4 filelock-3.8.2 fonttools-4.38.0 h11-0.14.0 hyperlink-21.0.0 incremental-22.10.0 itemadapter-0.7.0 itemloaders-1.0.6 jmespath-1.0.1 kiwisolver-1.4.4 lxml-4.9.2 matplotlib-3.6.2 numpy-1.24.0 outcome-1.2.0 packaging-22.0 pandas-1.5.2 parsel-1.7.0 protego-0.2.1 pyOpenSSL-22.1.0 pyasn1-0.4.8 pyasn1-modules-0.2.8 pycparser-2.21 pydantic-1.10.2 python-dateutil-2.8.2 queuelib-1.6.2 requests-file-1.5.1 selenium-4.7.2 service-identity-21.1.0 sniffio-1.3.0 sortedcontainers-2.4.0 tldextract-3.4.0 trio-0.22.0 trio-websocket-0.9.2 typer-0.7.0 typing-extensions-4.4.0 undetected-chromedriver-3.1.7 w3lib-2.1.1 websockets-10.4 wsproto-1.2.0 zope.interface-5.5.2
```

```
$eccoindex-cli --help
-bash: ecoindex-cli: command not found
```

Installations of Python3 and pip were done under root user. Installation of ecoindex-cli was done under user (fred) account.

Thanks for your help,

Fred

### Version

^3.6

### What OS do you use?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vvatelot** [comment]
Hello @fredlux55 can you try to logout / login and retry the command ?

**Comment by fredlux55** [comment]
Hi,

Yes this solve this issue. But after another one appear : 
```
ecoindex-cli analyze --url https://www.google.fr
📁️ Urls recorded in file `/tmp/ecoindex-cli/input/www.google.fr.csv`
There are 1 url(s), do you want to process? [Y/n]: Y
1 urls for 1 window size with 2 maximum workers
Processing  [####################################]  1/1  100%
Errors found: please look at /tmp/ecoindex-cli/logs/www.google.fr.log)

ExportFormat.csv
Traceback (most recent call last):

  File "/home/fred/.local/bin/ecoindex-cli", line 8, in <module>
    sys.exit(app())

  File "/home/fred/.local/lib/python3.10/site-packages/ecoindex_cli/cli/app.py", line 195, in analyze
    write_results_to_file(

  File "/home/fred/.local/lib/python3.10/site-packages/ecoindex_cli/files.py", line 69, in write_results_to_file
    file.write()

  File "/home/fred/.local/lib/python3.10/site-packages/ecoindex_cli/files.py", line 37, in write
    headers = self.results[0].__dict__

IndexError: list index out of range

```
Thanks

**Comment by vvatelot** [comment]
I get it: You have to install Google Chrome. It is a requirement of [ecoindex_scraper](https://github.com/cnumr/ecoindex_scrap_python/#requirements) but not explicit here for ecoindex_cli. To make it run, you can get inspiration from the test [Dockerfile](https://github.com/cnumr/ecoindex_cli/blob/eb84507686b8e9d5b6ab59790dcc1dd0fd1a467b/Dockerfile) I made this week:

```
export CHROME_VERSION=107.0.5304.121-1
apt-get update && apt-get -y install libpq-dev gcc wget
wget "https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb" \
    && apt-get install -y "./google-chrome-stable_${CHROME_VERSION}_amd64.deb" \
    && rm "google-chrome-stable_${CHROME_VERSION}_amd64.deb"
```

And then you have to run ecoindex with:
```
ecoindex-cli analyze --url https://www.ecoindex.fr --chrome-version 107
```

**Comment by vvatelot** [comment]
> Many thanks for your help : it works!

Great 🙂
