### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'click'

### ISSUE THREAD

**Issue by edouard-lopez** [cnumr/ecoindex_cli#225]
### What happened?

```
❯ poetry install && poetry shell
❯ source /home/edouard/.cache/pypoetry/virtualenvs/ecoindex-cli-f6zuBlXq-py3.10/bin/activate.fish
ecoindex-cli-f6zuBlXq-py3.10 ❯ poetry run ecoindex-cli
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/edouard/projects/explorations/ecoindex_cli/ecoindex_cli/cli/app.py", line 9, in <module>
    from click.exceptions import Exit
ModuleNotFoundError: No module named 'click'
```

### Version

Above 3.6

### What OS do you use?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by edouard-lopez** [comment]
Fixed by installing `click`:

```
poetry add click  
```

Now I got another error related to `undetected_chromedriver.v2`
