### ISSUE TITLE
[Bug]: json output + html report

### ISSUE THREAD

**Issue by revolunet** [cnumr/ecoindex_cli#259]
### What happened?

Look like combining `--export-format json` with `--html-export` breaks something

```
…/projects/mas/ecoindex_cli on  main [!?] 
➜ docker run -ti  --name ecoindex ecoindex ecoindex-cli analyze --url=https://xxx.fr --no-interaction --export-format json  --html-report
📁️ Urls recorded in file `/tmp/ecoindex-cli/input/xxx.fr.csv`
1 urls for 1 window size with 8 maximum workers
Processing  [####################################]  1/1  100%
ExportFormat.json
🙌️ File /tmp/ecoindex-cli/output/xxx.fr/2023-14-04_145533/results.json written !
Traceback (most recent call last):

  File "/usr/local/bin/ecoindex-cli", line 8, in <module>
    sys.exit(app())
             ^^^^^

  File "/usr/local/lib/python3.11/site-packages/ecoindex_cli/cli/app.py", line 200, in analyze
    Report(

  File "/usr/local/lib/python3.11/site-packages/ecoindex_cli/report/report.py", line 21, in __init__
    self.dataframe = read_csv(results_file)
                     ^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1778, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 230, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "pandas/_libs/parsers.pyx", line 808, in pandas._libs.parsers.TextReader.read_low_memory

  File "pandas/_libs/parsers.pyx", line 866, in pandas._libs.parsers.TextReader._read_rows

  File "pandas/_libs/parsers.pyx", line 852, in pandas._libs.parsers.TextReader._tokenize_rows

  File "pandas/_libs/parsers.pyx", line 1973, in pandas._libs.parsers.raise_parser_error

pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 3, saw 2

```

### Version

^3.6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vvatelot** [comment]
Hello @revolunet this bug should be fixed!
Sorry, the issue was closed automatically by the Pull Request. Let me know if you encounter other problems...

**Comment by revolunet** [comment]
nice thanks 🙏 possible to republish the docker image ? :p

**Comment by vvatelot** [comment]
Done 😉

**Comment by revolunet** [comment]
Thanks. results will be included in our "[best-practices dashboard](https://dashlord.fabrique.social.gouv.fr/)" next week

(was using a wrapper until now)
