### ISSUE TITLE
[Feature proposal] Support usage as a "checker" in a CI pipeline

### ISSUE THREAD

**Issue by Lucas-C** [cnumr/ecoindex_cli#338]
Hi!

Thank you for building & maintaining this tool 😊

**Context**
I'd like to use `ecoindex-cli` in a CI pipeline, in order to detect when regressions are introduced on my web project regarding the EcoIndex score.

**Suggested solution**
If `--fail-on-grade-below=A` is set, and the report grade is not A, `ecoindex-cli` displays a failure message and exit with a non-zero code.

A similar `--fail-on-score-below=` option could also be added.

What do you think of this idea?
I'd be happy to contribute a PR if you agree with this suggestion.

### Code of Conduct
- [X] I agree to follow this project's Code of Conduct

**Comment by vvatelot** [comment]
**🙏🏻 Praise:** Thank you for your contribution! Maybe you are more looking at something like https://github.com/cnumr/ecoindex-audit ?

**Comment by Lucas-C** [comment]
> **🙏🏻 Praise:** Thank you for your contribution! Maybe you are more looking at something like [cnumr/ecoindex-audit](https://github.com/cnumr/ecoindex-audit) ?

Thank you for the suggestion.
I tested it and got this error:
```
/home/user/.npm/_npx/dfb4c4b918f8f460/node_modules/ecoindex_puppeteer/dist/utils/EcoIndexDataHandler.js:88
            const isCachedOrData = response.fromDiskCache || response.fromServiceWorker || response.fromPrefetchCache || response.protocol === 'data';
                                            ^

TypeError: Cannot read properties of undefined (reading 'fromDiskCache')
    at EcoIndexDataHandler.onNetworkLoadingFinished (/home/user/.npm/_npx/dfb4c4b918f8f460/node_modules/ecoindex_puppeteer/dist/utils/EcoIndexDataHandler.js:88:45)
    at /home/user/.npm/_npx/dfb4c4b918f8f460/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/third_party/mitt/index.js:3:248
    at Array.map (<anonymous>)
    at Object.emit (/home/user/.npm/_npx/dfb4c4b918f8f460/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/third_party/mitt/index.js:3:232)
    at CDPSessionImpl.emit (/home/user/.npm/_npx/dfb4c4b918f8f460/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:87:22)
    at CDPSessionImpl._onMessage (/home/user/.npm/_npx/dfb4c4b918f8f460/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:441:18)
    at Connection.onMessage (/home/user/.npm/_npx/dfb4c4b918f8f460/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:269:25)
    at WebSocket.<anonymous> (/home/user/.npm/_npx/dfb4c4b918f8f460/node_modules/puppeteer/node_modules/puppeteer-core/lib/cjs/puppeteer/common/NodeWebSocketTransport.js:62:32)
    at callListener (/home/user/.npm/_npx/dfb4c4b918f8f460/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/home/user/.npm/_npx/dfb4c4b918f8f460/node_modules/ws/lib/event-target.js:209:9)
```

Moreover, I'm already in a Python ecosystem, so having to install NodeJS + NPM + 120Mo of JS dependencies (based on `du -sh ~/.npm/_npx/dfb4c4b918f8f460/`) seems a bit unnecessary...
Not quite frugal 😅

Also, are you suggesting to use another tool because this one is not maintained / will not evolve?

**Comment by vvatelot** [comment]
Sorry, I won't be able to help you with this error. I suggest you to open an issue on the project directly... :slightly_frowning_face: 

Maybe we can add options as you propose to this tool, but, as it is supposed to analyze multiple pages, what would be the policy of failing? 
- Fails if one page of all is below the target ?
- Fails if all of the pages are below the targt ?
- ...

**Comment by Lucas-C** [comment]
The 1st seems to make the most sense to me: fails if any page is below the target.
